### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by AaronYang2333** [knugraha/Rollercoin#1]
hi bro,

i have to say this is nice project, and when I run your code, there was a keyError exception raise, did you meet the same situation?

I think it because the image mismatch right ?

**Comment by AaronYang2333** [comment]
![123131](https://user-images.githubusercontent.com/24391143/125182423-8873b200-e240-11eb-9308-4ecdc7c4cd5f.PNG)

**Comment by AaronYang2333** [comment]
also I found matchTemplates method is super slow. it is hard for bot to crack the level 8 game. i plan to train a CNN model to do this task.

**Comment by knugraha** [comment]
matchTemplates method supper slow and never finish level 8 game and this project temporary i close until new version i release.
make sure you install all the libraries in requirements.txt, if you still find errors, you can contact me again saya

**Comment by AaronYang2333** [comment]
[Actuall I can crack level 10 already ](https://www.youtube.com/watch?v=0LgMaCDIAsk)
